### ISSUE TITLE
new Hackage release

### ISSUE THREAD

**Issue by Jonplussed** [peti/hsyslog#11]
The latest available version of [hsyslog on Hackage][1] is 2.0. Is the current code stable enough that you would consider a new Hackage release? If not, what changes would you like to make it suitable?

Thanks!

  [1]: http://hackage.haskell.org/package/hsyslog

**Comment by peti** [comment]
I'll make a new release in the next couple of days. I haven't had time to actually read most of the modified source code yet. :disappointed: I'll do it within the next week or so and then release a new version.

**Comment by Jonplussed** [comment]
Thanks, and of course no hurries.

**Comment by qrilka** [comment]
hi @peti - any updates on this one?

**Comment by peti** [comment]
Oops, I am sorry about the delay! The new release is out: http://hackage.haskell.org/package/hsyslog.
