### ISSUE TITLE
Don't abuse the Enum class to map syslog priorities to their respective bit value

### ISSUE THREAD

**Issue by peti** [peti/hsyslog#5]
Either, the definition of the `Enum` class instance for `Priority` must be fixed so that use cases like `enumFrom Debug` don't crash any more, we should find a better way to express the relationship between Priorities and Integers.

**Comment by Jonplussed** [comment]
I don't believe this is still an issue. Functions like `enumFrom` and `enumFromThen` work fine with Priorities, Options, and other syslog data types. If you know of any examples that still break I'd be happy to take a look.

**Comment by peti** [comment]
Closing this issue since it has been fixed a while ago.
