### ISSUE TITLE
Support logging ByteStrings, which can be done more efficiently than logging Strings

### ISSUE THREAD

**Issue by peti** [peti/hsyslog#7]
A (non-lazy) `ByteString` is essentially a C string, so we can pass it on to `syslog` without any processing. Logging of `String`-like objects can still be implemented on top of that.

**Comment by lpsmith** [comment]
`useAsCString` is still quite a bit faster than `withCString`,  because the former is a simple memcpy whereas the latter involves traversing a linked list of characters.

**Comment by feuerbach** [comment]
Oh, for sure!

**Comment by jberryman** [comment]
Logging `ByteString`s would be a more useful API I think, but worth keeping in mind the overhead of writing to the syslog socket (microseconds). I'm not sure anyone needs this who hasn't already implemented some batched log writing solution.
